name: Android CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run tests
      run: ./gradlew test --stacktrace
      
    - name: Run lint
      run: ./gradlew lintDebug
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

  build-release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create keystore.properties
      if: ${{ env.SIGNING_KEY_ALIAS != '' }}
      run: |
        echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> keystore.properties
        echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> keystore.properties
        echo "storeFile=../app-release.keystore" >> keystore.properties
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        
    - name: Create release keystore
      if: ${{ env.SIGNING_KEY_ALIAS != '' }}
      run: |
        echo "${{ secrets.SIGNING_KEYSTORE }}" | base64 --decode > app-release.keystore
      env:
        SIGNING_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
        
    - name: Build release bundle
      run: ./gradlew bundleRelease --stacktrace
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
        
    - name: Upload Bundle artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-bundle
        path: app/build/outputs/bundle/release/*.aab